# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.delete_all

user_1 = User.create(first_name: 'John', last_name: 'Smith', username: 'johnsmith', email: 'john.smith@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)
user_2 = User.create(first_name: 'Joseph', last_name: 'Myles', username: 'josephmyles', email: 'joseph.myles@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)
user_3 = User.create(first_name: 'Dominic', last_name: 'Clark', username: 'dominicclark', email: 'dominic.clark@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)
user_4 = User.create(first_name: 'Zed', last_name: 'Horne', username: 'zedhorne', email: 'zed.horne@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)
user_5 = User.create(first_name: 'Weston', last_name: 'Akers', username: 'westonakers', email: 'weston.akers@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)
user_6 = User.create(first_name: 'Rachael', last_name: 'Lowry', username: 'rachaellowry', email: 'rachael.lowry@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)
user_7 = User.create(first_name: 'Sarah', last_name: 'Chapman', username: 'sarahchapman', email: 'sarah.chapman@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)
user_8 = User.create(first_name: 'Megan', last_name: 'Hayley', username: 'meganhayley', email: 'meganhayley@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)
user_9 = User.create(first_name: 'Gabriella', last_name: 'Nowell', username: 'gabriellanowell', email: 'gabriella.nowell@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)
user_10 = User.create(first_name: 'Chloe', last_name: 'Morris', username: 'chloemorris', email: 'chloe.morris@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)
user_11 = User.create(first_name: 'Nadia', last_name: 'Dean', username: 'nadiadean', email: 'nadia.dean@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)
user_12 = User.create(first_name: 'Pippa', last_name: 'Forest', username: 'pippaforest', email: 'pippa.forest@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)
user_13 = User.create(first_name: 'Paulina', last_name: 'Mason', username: 'paulinamason', email: 'paulina.mason@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)
user_14 = User.create(first_name: 'Brendon', last_name: 'Rogers', username: 'brendonrogers', email: 'brendon.rogers@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)
user_15 = User.create(first_name: 'Max', last_name: 'Towner', username: 'maxtowner', email: 'max.towner@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)
user_16 = User.create(first_name: 'Freddy', last_name: 'Russell', username: 'freddyrussell', email: 'freddy.russell@gmail.com', password: 'password', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis leo sit amet malesuada gravida. Aenean tortor libero, bibendum quis libero convallis, interdum convallis ligula. Proin gravida libero eget quam imperdiet cursus.', created_at: Time.now, last_sign_in_at: Time.now)